<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'argument_resolver.service' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/ServiceValueResolver.php';

return $this->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\ServiceLocator(array('App\\Controller\\ContactController::contactValidation' => function () {
    return ($this->privates['.service_locator.3FFBWiy'] ?? $this->load('get_ServiceLocator_3FFBWiyService.php'));
}, 'App\\Controller\\SecurityController::login' => function () {
    return ($this->privates['.service_locator.3rpVPSY'] ?? $this->load('get_ServiceLocator_3rpVPSYService.php'));
}, 'App\\Controller\\ContactController:contactValidation' => function () {
    return ($this->privates['.service_locator.3FFBWiy'] ?? $this->load('get_ServiceLocator_3FFBWiyService.php'));
}, 'App\\Controller\\SecurityController:login' => function () {
    return ($this->privates['.service_locator.3rpVPSY'] ?? $this->load('get_ServiceLocator_3rpVPSYService.php'));
})));
